### ISSUE TITLE
Incorrect vertical positioning for dropdowns inside iron-list

### ISSUE THREAD

**Issue by WrinklyNinja** [PolymerElements/iron-dropdown#62] opened 2016-02-16 21:19 UTC
If a `<paper-menu-button>` is placed inside an `<iron-list>` item, the internal `<iron-dropdown>` is displayed with the wrong vertical offset unless the item is aligned to the top of the viewport.

## Expected outcome

The dropdown for each list item should be displayed over the item's menu button.

## Actual outcome

The dropdown for any list item that is not aligned to the top of the viewport is vertically offset from the menu button's position.

This offset is equal to the dropdown's list item's `getBoundingClientRect().top` value, ie. how far the list item is from the top of the viewport. The offset can be negative, if the list item is only partially visible at the top of the viewport.

The dropdown's `top` CSS property is set to the `getBoundingClientRect().top` value for the dropdown's position target (which is the `<paper-menu-button>`). This value is relative to the viewport, but the CSS is applied relative to the list item element. I'm not sure why this happens.

## Steps to reproduce

[Here's a jsbin](https://jsbin.com/pozidaluqo/edit?html,output) demonstrating the issue - ignore the z-positioning of the menus, that's an unrelated issue. I can reproduce the issue in Edge, Firefox and Chrome (other browsers untested).

**Comment by WrinklyNinja** [comment] 2016-02-17 22:09
After a big more digging, I've found the issue is because transformed elements (which `<iron-list>` items are) [create new containing blocks](http://stackoverflow.com/a/15256339) for any `position: fixed` children (which `<iron-dropdown>` is).

**Comment by stephenbunch** [comment] 2016-02-18 09:11
I just ran into a similar problem where the top position was way off because another parent on the page had a transform applied. I'm not sure what the right fix is other than making sure no transforms are applied to parent elements when the dropdown is shown. This seems like an architectural problem with the component. Personally, I would have avoided solutions that relied on `position: fixed`, but I'm not familiar with the requirements of this component.

**Comment by WrinklyNinja** [comment] 2016-02-18 18:45
I've [managed to fix this](https://github.com/loot/iron-dropdown/commit/a8c18381b9db905629d52bacb53928b4e828fd00) by detecting when an ancestor element is transformed, and calculating different position rectangle values relative to that element.

However, I can't submit a PR because I can't get WCT set up properly, so can't write a test for the bug.

**Comment by cdata** [comment] 2016-02-18 22:12
Hey, thanks for the awesome bug report and the thorough investigation. I'm going to close this issue because it is a dupe of https://github.com/PolymerElements/iron-fit-behavior/issues/33. Also, /cc @valdrinkoshi who is working on a fix here https://github.com/PolymerElements/iron-fit-behavior/pull/34

**Closed by cdata** 2016-02-18 22:12 UTC
