### ISSUE TITLE
Dropdown position is wrong when the page has a vertical scrollbar

### ISSUE THREAD

**Issue by mderriey** [PolymerElements/iron-dropdown#73] opened 2016-04-01 10:30 UTC
### Description

The placement of the dropdown is wrong when an `<iron-dropdown>` is on a page with a vertical scrollbar. `IronDropdownScrollManager` disables the vertical scrollbar after the dropdown has been shown. This means that the dropdown is actually slightly horizontally shifted from its correct position.

### Expected outcome

The dropdown position should be computed after `IronDropdownScrollmanager` disables scrolling on the page

### Actual outcome

The dropdown position is computed before `IronDropdownScrollmanager` disables scrolling on the page.

### Live Demo

[Terrible demo, sorry](https://output.jsbin.com/zoheniwozo)

### Steps to reproduce

1. Open the demo page
2. Open the DevTools
3. Click on the `Open dropdown` button
4. Slightly resize the viewport
5. Observe how the dropdown is repositioned as soon as the resize takes place

### Browsers Affected
- [X] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [x] Edge
- [X] IE 11
- [ ] IE 10

I don't know if the others are affected.

### Special note

Let me know if I can be of further help!
Thanks :+1:

**Comment by hzmnet** [comment] 2016-07-03 06:47
your code is start with <paper-menu-button> end with </iron-dropdown>

**Comment by valdrinkoshi** [comment] 2016-07-06 23:48
Closing this as it's a duplicate of https://github.com/PolymerElements/iron-dropdown/issues/54

**Closed by valdrinkoshi** 2016-07-06 23:48 UTC
