### ISSUE TITLE
iron-dropdown doesn't scroll when used inside another custom element (shadow dom only)

### ISSUE THREAD

**Issue by hensom** [PolymerElements/iron-dropdown#27] opened 2015-09-29 23:47 UTC
I've found an interesting behavior in iron-dropdown when used with the shadow dom. If you create a dropdown whose inner content is so long as to require scrolling you will find that the dropdown will refuse to scroll the content. This only happens when the dropdown is placed inside of another Polymer element and you are using the shadow dom. I cannot reproduce this if the dropdown is in the main document or if I use the shady dom. I suspect I could work around this issue if I disabled scroll locking, but it seems sub-ideal as is.

Here's a script that reproduces the issue.
http://jsbin.com/xatuyi/edit?html,output

**Comment by Saulis** [comment] 2015-10-27 12:47
I have problem which might be related, in my case Polymer throws errors when I even try to scroll.

Given a simple component:

```html
<!doctype html>
<html>

<head>
  <script src='../../webcomponentsjs/webcomponents-lite.js'></script>
  <link href='../../iron-dropdown/iron-dropdown.html' rel='import'>
</head>

<body>

  <dom-module id="x-foo">
    <template>
      <iron-dropdown id="dropdown" opened='true'>
        <div id="dropdown-content">
          <content>
        </div>
      </iron-dropdown>
    </template>
  </dom-module>

  <x-foo>
    <div></div>
  </x-foo>

  <script>
    document.addEventListener('WebComponentsReady', function() {
      Polymer({
        is: 'x-foo'
      });
    });
  </script>

</body>

</html>
```

When I open this file with `?dom=shadow` and just try to scroll, console gets filled with 
`Uncaught TypeError: this.node.querySelectorAll is not a function` which is caused by `iron-dropdown` trying to call `querySelectorAll` on `#textNode`s. I've witnessed the same behaviour on IE11 without `dom=shadow`

The problem can be worked around by removing all white spaces between the elements inside `<content>`

_Tested with: Polymer 1.1.5 and iron-dropdown 1.0.6_

**Comment by cdata** [comment] 2015-10-27 19:14
Hi. Thanks for the test case. I will take a look.

**Comment by cdata** [comment] 2015-12-14 23:09
I did some poking, and I discovered that there may be a Chrome bug related to `wheel` events in ShadowDOM. I have filed https://code.google.com/p/chromium/issues/detail?id=569707 and will continue investigating as I get feedback on that bug report.

**Comment by freshp86** [comment] 2016-01-15 19:19
FYI, I think I have a candidate fix for this. Will be sending a PR shortly.

**Comment by danbeam** [comment] 2016-01-19 20:07
ping: this is affecting Chrome's new Polymer-based Settings page

do we need to re-jigger our layout or can we massage the event handling code?

/cc @tjsavage

**Comment by notwaldorf** [comment] 2016-01-19 22:27
@danbeam There's already a PR out to fix this (https://github.com/PolymerElements/iron-dropdown/pull/49), should be merged pretty soon!

**Comment by valdrinkoshi** [comment] 2016-02-19 18:21
Closing this as got fixed and is available in `v1.2.0`

**Closed by valdrinkoshi** 2016-02-19 18:21 UTC
Labels: code-yellow, p0 - critical

**Comment by rochdev** [comment] 2016-02-22 21:06
I am still having the same issue with `v1.2.0`

**Comment by valdrinkoshi** [comment] 2016-02-22 22:06
I'm testing your jsbin on mac, and I cannot reproduce it http://jsbin.com/pikoxu/1/edit?html,output
![dropdown](https://cloud.githubusercontent.com/assets/6173664/13234443/7adf423a-d96d-11e5-9168-9e6c6c6769e3.gif)
