### ISSUE TITLE
the component should use position:absolute; 

### ISSUE THREAD

**Issue by hzmnet** [PolymerElements/iron-dropdown#134] opened 2017-04-23 15:41 UTC
some situation it will keep the position at the center of the screen when the scroll bar at the middle and it is  open at the top

### Browsers Affected

- [X ] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by valdrinkoshi** [comment] 2018-03-30 07:01
Duplicate of #128, see more details here https://github.com/PolymerElements/iron-dropdown/issues/128#issuecomment-377461543

**Closed by valdrinkoshi** 2018-03-30 07:01 UTC
