### ISSUE TITLE
Overflow on dropdown

### ISSUE THREAD

**Issue by Mikanoshi** [PolymerElements/iron-dropdown#52] opened 2016-01-19 18:00 UTC
Overflow: hidden on body? Seriously?

![_polymer](https://cloud.githubusercontent.com/assets/5113439/12427267/1c249ede-bf00-11e5-838d-5006356d63f9.gif)

**Comment by cdata** [comment] 2016-01-29 23:39
This is a very non-constructive and unhelpful bug report. Please refer to our [contributing guidelines](https://github.com/PolymerElements/iron-dropdown/blob/master/CONTRIBUTING.md) and our [code of conduct](https://github.com/Polymer/polymer/wiki/Code-of-Conduct) before reporting issues in the future.

This is a dupe of https://github.com/PolymerElements/iron-dropdown/issues/54 (please consider reading that issue for an example of how to report issues in a constructive manner).

**Closed by cdata** 2016-01-29 23:39 UTC

**Comment by Mikanoshi** [comment] 2016-01-29 23:56
It's not a bug report. This was obviously an intentional and very poor solution for some problem. GIF demonstrates everything perfectly, I just expressed my genuine surprise and disappointment :)
