### ISSUE TITLE
position issues with translate transform

### ISSUE THREAD

**Issue by frankstolle** [PolymerElements/iron-dropdown#56] opened 2016-02-01 19:57 UTC
The fixed position is not correct calculated if you use translation transform. Example can be viewed here: https://jsfiddle.net/sqo9km2q/

**Comment by cdata** [comment] 2016-02-03 22:02
Hi, thanks for reporting. This is a dupe of https://github.com/PolymerElements/iron-dropdown/issues/56, so I am going to close it.

**Closed by cdata** 2016-02-03 22:02 UTC

**Comment by frankstolle** [comment] 2016-02-04 06:25
Hmm because this is acutally #56, where is the dupe?

**Comment by frankstolle** [comment] 2016-02-06 13:07
Can you please link the correct issue which is duplicated? You linked the issue itself.

**Comment by cdata** [comment] 2016-02-08 23:49
Sorry! The correct issue is https://github.com/PolymerElements/iron-fit-behavior/issues/33
