### ISSUE TITLE
hides body overflow on expand

### ISSUE THREAD

**Issue by NicolasRannou** [PolymerElements/iron-dropdown#81] opened 2016-05-05 11:07 UTC
### Description

The iron-dropdown cause the body overflow to be hidden on open.

It also affects teh paper-dropdown: https://github.com/PolymerElements/paper-dropdown-menu/issues/130
### Expected outcome

It shouldn't affect the body overflow.

### Actual outcome

The overflow property of the body is hidden.

### Live Demo

https://elements.polymer-project.org/elements/iron-dropdown?view=demo:demo/index.html&active=iron-dropdown

### Steps to reproduce
1- Reduce the window size to have a right scroll bar displayed.
2- Click on a drop-down

### Browsers Affected
- [x] Chrome
- [x] Firefox
- [x] Safari 9
- [x] Safari 8
- [x] Safari 7
- [x] Edge
- [x] IE 11
- [x] IE 10

**Comment by NicolasRannou** [comment] 2016-05-06 02:36
Fun fact, on my laptop screen it looks fine, because in chrome, the scroll bar is different whether you are on a small screen or not. (I guess)

It doesn't look good on my 2nd monitor...

**Comment by valdrinkoshi** [comment] 2016-06-30 23:23
This looks like a duplicate of https://github.com/PolymerElements/iron-dropdown/issues/54
I'll close this

**Closed by valdrinkoshi** 2016-06-30 23:23 UTC
